### ISSUE TITLE
Tribler API research

### ISSUE THREAD

**Issue by rjwvandenberg** [rjwvandenberg/PlebNet#8]
REST api is available for many of the needed parameters, see source code
Tribler/Core/modules/restapi
and docs
http://tribler.readthedocs.io/ (does not include market yet)

A good option would be to implement a plebnet twisted plugin, using tribler plugin as a basis to setup the exposing ports and services needed.

**Comment by Jaapp-** [comment]
Twisted plugin has been crated, configuration still needs some work.
